// Generated by CoffeeScript 1.4.0
(function() {
  var _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if ((_ref = window.Amoeba) == null) {
    window.Amoeba = {};
  }

  Amoeba.GraphicsPaper = (function() {

    function GraphicsPaper(divHolder, attr) {
      this.divHolder = divHolder;
      if (attr == null) {
        attr = null;
      }
      this._fadePoint = __bind(this._fadePoint, this);

      this.clearPoints = __bind(this.clearPoints, this);

      this.clearAll = __bind(this.clearAll, this);

      this.pulsatePoints = __bind(this.pulsatePoints, this);

      if (attr == null) {
        attr = {
          fill: "90-#aaf-#004",
          stroke: "#f99"
        };
      }
      this.paper = Raphael(this.divHolder);
      this.paper.rect(0, 0, this.width(), this.height()).attr(attr);
      this.points = [];
    }

    GraphicsPaper.prototype.width = function() {
      if (this.paper.canvas.clientWidth) {
        return this.paper.canvas.clientWidth;
      } else {
        return this.paper.width;
      }
    };

    GraphicsPaper.prototype.height = function() {
      if (this.paper.canvas.clientHeight) {
        return this.paper.canvas.clientHeight;
      } else {
        return this.paper.height;
      }
    };

    GraphicsPaper.prototype.addPoints = function(points, radius, color) {
      var circle, point, _i, _len, _results;
      if (color == null) {
        color = "#f00";
      }
      _results = [];
      for (_i = 0, _len = points.length; _i < _len; _i++) {
        point = points[_i];
        circle = this.paper.circle(point.x, point.y, radius);
        circle.attr({
          fill: color,
          stroke: "none"
        });
        _results.push(this.points.push(circle));
      }
      return _results;
    };

    GraphicsPaper.prototype.pulsatePoints = function() {
      var point, _i, _len, _ref1, _results;
      _ref1 = this.points;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        point = _ref1[_i];
        _results.push(this._fadePoint(true, point));
      }
      return _results;
    };

    GraphicsPaper.prototype.clearAll = function() {
      return this.paper.clear();
    };

    GraphicsPaper.prototype.clearPoints = function() {
      var point, _i, _len, _ref1, _results;
      _ref1 = this.points;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        point = _ref1[_i];
        _results.push(point.remove());
      }
      return _results;
    };

    GraphicsPaper.prototype._fadePoint = function(out, point) {
      var fadeIn, fadeOut,
        _this = this;
      fadeOut = Raphael.animation({
        transform: "s2",
        "fill-opacity": 1
      }, 600, "<", function() {
        return _this._fadePoint(!out, point);
      });
      fadeIn = Raphael.animation({
        transform: "s1",
        "fill-opacity": 0.1
      }, 600, ">", function() {
        return _this._fadePoint(!out, point);
      });
      point.stop();
      if (out) {
        return point.animate(fadeOut);
      } else {
        return point.animate(fadeIn);
      }
    };

    return GraphicsPaper;

  })();

  Amoeba.Point = (function() {

    function Point(x, y) {
      this.x = x;
      this.y = y;
    }

    Point.prototype.toString = function() {
      return "(" + this.x + ", " + this.y + ")";
    };

    Point.prototype.distance = function(point2) {
      var xs, ys;
      xs = point2.x - this.x;
      xs = xs * xs;
      ys = point2.y - this.y;
      ys = ys * ys;
      return Math.sqrt(xs + ys);
    };

    return Point;

  })();

  Amoeba.Pair = (function() {

    function Pair(left, right) {
      this.left = left;
      this.right = right;
    }

    Pair.prototype.toString = function() {
      return "(" + this.left + ", " + this.right + ")";
    };

    return Pair;

  })();

  Amoeba.Rect = (function() {

    function Rect(x, y, w, h) {
      this.x = x;
      this.y = y;
      this.w = w;
      this.h = h;
    }

    Rect.prototype.toString = function() {
      return "(x:" + this.x + ", y:" + this.y + ", w:" + this.w + ", h:" + this.h + ")";
    };

    return Rect;

  })();

  Amoeba.Graphics = (function() {

    function Graphics() {}

    Graphics.toDegrees = function(angle) {
      return angle * (180 / Math.PI);
    };

    Graphics.toRadians = function(angle) {
      return angle * (Math.PI / 180);
    };

    Graphics.pointForAngle = function(degrees, radius, centerPoint) {
      var cosValue, sinValue;
      cosValue = Math.cos(Amoeba.Graphics.toRadians(degrees));
      sinValue = Math.sin(Amoeba.Graphics.toRadians(degrees));
      return new Amoeba.Point(centerPoint.x + (cosValue * radius), centerPoint.y + (sinValue * radius));
    };

    Graphics.normalizePath = function(path) {
      var bBox, theMatrix, transformString;
      bBox = Raphael.pathBBox(path);
      theMatrix = new Raphael.matrix();
      theMatrix.translate(-bBox.x, -bBox.y);
      transformString = theMatrix.toTransformString();
      path = Raphael.transformPath(path, transformString);
      return path;
    };

    Graphics.scalePath = function(path, amountX, amountY) {
      var bBox, theMatrix, transformString;
      bBox = Raphael.pathBBox(path);
      theMatrix = new Raphael.matrix();
      theMatrix.scale(amountX, amountY);
      transformString = theMatrix.toTransformString();
      path = Raphael.transformPath(path, transformString);
      return path;
    };

    Graphics.translatePath = function(path, amountX, amountY) {
      var bBox, theMatrix, transformString;
      bBox = Raphael.pathBBox(path);
      theMatrix = new Raphael.matrix();
      theMatrix.translate(amountX, amountY);
      transformString = theMatrix.toTransformString();
      path = Raphael.transformPath(path, transformString);
      return path;
    };

    Graphics.rotatePath = function(path, degrees) {
      var bBox, theMatrix, transformString;
      bBox = Raphael.pathBBox(path);
      theMatrix = new Raphael.matrix();
      theMatrix.rotate(degrees, bBox.x + (bBox.width / 2), bBox.y + (bBox.height / 2));
      transformString = theMatrix.toTransformString();
      path = Raphael.transformPath(path, transformString);
      return path;
    };

    Graphics.circleWithFourPoints = function(x, y, r) {
      var centerPoint, degrees, point, result, _i, _len, _ref1;
      centerPoint = new Amoeba.Point(x, y);
      result = null;
      _ref1 = [0, 90, 180, 270, 360];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        degrees = _ref1[_i];
        point = this.pointForAngle(degrees, r, centerPoint);
        if (!(result != null)) {
          result = "M" + (x + r) + ", " + y;
        } else {
          result += "A" + r + "," + r + ",0,0,1," + point.x + "," + point.y;
        }
      }
      result += "z";
      result = this.rotatePath(result, -135);
      return result;
    };

    Graphics.rectWithFourPoints = function(x, y, w, h) {
      var result;
      result = "M" + x + ", " + y;
      result += "l" + w + ", 0";
      result += "l0, " + h;
      result += "l" + (-w) + ", 0";
      result += "l0, " + (-h);
      return result;
    };

    return Graphics;

  })();

}).call(this);
