// Generated by CoffeeScript 1.4.0
(function() {
  var PathAnimation, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  if ((_ref = window.Amoeba) == null) {
    window.Amoeba = {};
  }

  Amoeba.Animations = (function() {

    function Animations() {
      this._createAnimations = __bind(this._createAnimations, this);

      this._diamondPath = __bind(this._diamondPath, this);

    }

    Animations.prototype.setupAnimations = function() {
      this.paper = Raphael(0, 280, 850, 650);
      this.paper.rect(0, 0, 850, 650).attr({
        fill: "90-#aaf-#004",
        stroke: "#f99",
        title: "background"
      });
      return this._createAnimations();
    };

    Animations.prototype.doAnimate = function() {
      return this.animations.forEach(function(el) {
        return el.animate();
      });
    };

    Animations.prototype.setupPathFields = function() {
      var _this = this;
      Amoeba.oneText = $("#one");
      Amoeba.twoText = $("#two");
      Amoeba.oneText.val(gearPath);
      Amoeba.twoText.val(circleGearPath);
      $("#gears").on("click", function(event) {
        Amoeba.oneText.val(gearPath);
        Amoeba.twoText.val(circleGearPath);
        return _this.doAnimate();
      });
      $("#rects").on("click", function(event) {
        Amoeba.oneText.val(makeRectanglePath(0, 0, 100, 500));
        Amoeba.twoText.val(makeRectanglePath(0, 0, 200, 300));
        return _this.doAnimate();
      });
      $("#example1").on("click", function(event) {
        var result;
        result = "M0,0c11,0 20,9 20,20c0,11 -9,20 -20,20c-11,0 -20-9 -20-20c0-11 9-20 20-20z";
        Amoeba.oneText.val(result);
        result = _this._diamondPath(20);
        Amoeba.twoText.val(result);
        return _this.doAnimate();
      });
      $("#example2").on("click", function(event) {
        var result;
        result = makeCirclePath(0, 0, 20);
        Amoeba.oneText.val(result);
        result = _this._diamondPath(20);
        Amoeba.twoText.val(result);
        return _this.doAnimate();
      });
      $("#example3").on("click", function(event) {
        var result;
        result = "M0,0 h-150 a150,150 0 1,0 150,-150z";
        Amoeba.oneText.val(result);
        result = _this._diamondPath(200);
        Amoeba.twoText.val(result);
        return _this.doAnimate();
      });
      $("#revDiamond").on("change", function(event) {
        var result;
        result = _this._diamondPath(200);
        Amoeba.twoText.val(result);
        _this._createAnimations();
        return _this.doAnimate();
      });
      return $("#run").on("click", function(event) {
        return _this.doAnimate();
      });
    };

    Animations.prototype._diamondPath = function(width) {
      var result;
      if (width == null) {
        width = 20;
      }
      result = "M0,0l" + width + "," + width + " -" + width + "," + width + " -" + width + "-" + width + "z";
      if (jQuery('#revDiamond').is(':checked')) {
        result = "M0,0l-" + width + "," + width + " " + width + "," + width + " " + width + "-" + width + "z";
        console.log("reversed");
      }
      return result;
    };

    Animations.prototype._createAnimations = function() {
      var num, _i, _len, _ref1;
      if ((this.animations != null)) {
        _ref1 = this.animations;
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          num = _ref1[_i];
          num.remove();
        }
      }
      return this.animations = [new PathAnimation("#44f", 0, this.paper), new PathAnimation("#f31", 420, this.paper)];
    };

    return Animations;

  })();

  PathAnimation = (function() {

    function PathAnimation(fillColor, offset, paper) {
      var _this = this;
      this.fillColor = fillColor;
      this.offset = offset;
      this.pathSwitch = true;
      this.mainPath = paper.path(this.pathOne(this.offset)).attr({
        fill: this.fillColor
      });
      this.mainPath.node.onclick = function() {
        _this.animate();
        return _this.mainPath.toFront();
      };
    }

    PathAnimation.prototype.remove = function() {
      return this.mainPath.remove();
    };

    PathAnimation.prototype.animate = function() {
      var thePath;
      if (+(this.pathSwitch = !this.pathSwitch)) {
        thePath = this.pathOne(this.offset);
      } else {
        thePath = this.pathTwo(this.offset);
      }
      return this.mainPath.animate({
        path: thePath,
        fill: this.fillColor
      }, 400, "<>");
    };

    PathAnimation.prototype.pathOne = function(offset) {
      var result;
      result = Amoeba.oneText.val();
      result = normalizePath(result);
      result = translatePath(result, offset, 0);
      return result;
    };

    PathAnimation.prototype.pathTwo = function(offset) {
      var result;
      result = Amoeba.twoText.val();
      result = normalizePath(result);
      result = translatePath(result, offset, 0);
      return result;
    };

    return PathAnimation;

  })();

}).call(this);
